# Project information
site_name: 东林机电辩论队
site_description: 东北林业大学机电辩论队
site_url: https://ittuann.github.io/NEFU-CMEE-DebateTeam/

# Repository
repo_name: ittuann/NEFU-CMEE-DebateTeam
repo_url: https://github.com/ittuann/NEFU-CMEE-DebateTeam
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - instant
    - header.autohide
    - search.suggest
    - search.share
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    primary: blue
    accent: blue
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_author: ittuann
copyright: CC BY-NC-SA 4.0

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.def_list
  - meta
  - toc:
      permalink: true

plugins:
  - search:
      lang: ja
      indexing: titles
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - awesome-pages

# Extra
extra:
  social:
    - icon: fontawesome/brands/trello
      link: https://trello.com
    - icon: fontawesome/brands/blogger-b
      link: https://ittuann.github.io
    - icon: fontawesome/brands/github
      link: https://github.com/ittuann

# Navigation
nav:
  - 首页: index.md
  # - 贡献指南:
  - 辩论类型:
      - 事实辩: type/factual.md
