name: Prettify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      - name: Inclusiveness Analyzer
        uses: microsoft/InclusivenessAnalyzer@v1.0.1

      - name: Prettify markdown
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{yml,md}
          commit_message: "Automatically Prettified Markdown"
