name: Prettify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettify:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: true

    steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Inclusiveness Analyzer
        uses: microsoft/InclusivenessAnalyzer@v1.0.1

      - name: Prettify markdown
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{yml,md}
          commit_message: "Automatically Prettified Markdown"
